---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    OCI_CLI_AUTH: "instance_principal"
  roles:
   - data-products-deploy
